name: Build and Upload to Nexus

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Find JAR file
        id: find-jar
        run: |
          # Find JAR files that start with 'ParadiseClient'
          JAR_FILES=(build/libs/ParadiseClient*.jar)
          if [ ${#JAR_FILES[@]} -ne 1 ]; then
            echo "Error: Expected exactly one JAR file starting with 'ParadiseClient', found ${#JAR_FILES[@]} files."
            exit 1
          fi
          JAR_FILE="${JAR_FILES[0]}"
          JAR_NAME=$(basename "$JAR_FILE")
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      - name: Upload artifact to Nexus
        run: |
          curl -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
               --upload-file ${{ env.JAR_FILE }} \
               https://repo.nexus-craft.org/ParadiseClient/${{ env.JAR_NAME }}
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
